version: '2.1'
services:
  rbd-dns:
    image: {{ pillar['private-image-domain'] }}/{{ pillar['rainbond-modules']['rbd-dns']['image'] }}:{{ pillar['rainbond-modules']['rbd-dns']['version'] }}
    container_name: rbd-dns
    mem_limit: 1024M
    environment:
      - VERBOSE=true
    command:
    - --kubecfg-file=/etc/kubernetes/admin.kubeconfig
    - --v=3
    - --healthz-port=8089
    - --nameservers={{ pillar.dns.get('current','114.114.114.114') }},{{ pillar.dns.slave }}
    - --recoders=goodrain.me={{ pillar['master-private-ip'] }},*.goodrain.me={{ pillar['master-private-ip'] }}
    volumes:
    - {{ pillar['rbd-path'] }}/etc/kubernetes/kubecfg:/etc/kubernetes
    logging:
      driver: json-file
      options:
        max-size: 50m
        max-file: '3'
    network_mode: host
    restart: always
  rbd-hub:
    image: {{ pillar['private-image-domain'] }}/{{ pillar['rainbond-modules']['rbd-registry']['image'] }}:{{ pillar['rainbond-modules']['rbd-registry']['version'] }}
    container_name: rbd-hub
    volumes:
    - /grdata/services/registry:/var/lib/registry
    logging:
      driver: json-file
      options:
        max-size: 50m
        max-file: '3'
    network_mode: host
    restart: always
  rbd-repo:
    image: {{ pillar['private-image-domain'] }}/{{ pillar['rainbond-modules']['rbd-repo']['image'] }}:{{ pillar['rainbond-modules']['rbd-repo']['version'] }}
    container_name: rbd-repo
    volumes:
    - /grdata/services/artifactory-{{ grains['nodename'] }}:/var/opt/jfrog/artifactory
    logging:
      driver: json-file
      options:
        max-size: 50m
        max-file: '3'
    network_mode: host
    restart: always
{% if grains['id'] == "manage01" %}
  rbd-db:
    image: {{ pillar['private-image-domain'] }}/{{ pillar['database']['mysql']['image'] }}:{{ pillar['database']['mysql']['version'] }}
    container_name: rbd-db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    volumes:
    - {{ pillar['rbd-path'] }}/data/rbd-db:/data
    - {{ pillar['rbd-path'] }}/etc/rbd-db:/etc/mysql
    logging:
      driver: json-file
      options:
        max-size: 50m
        max-file: '3'
    network_mode: host
    restart: always
{% endif %}