region_api:
  endpoints:
    - https://region.goodrain.me:8443
  client-ca-file: {{ pillar['rbd-path'] }}/etc/rbd-api/region.goodrain.me/ssl/ca.pem
  tls-cert-file:  {{ pillar['rbd-path'] }}/etc/rbd-api/region.goodrain.me/ssl/client.pem
  tls-private-key-file:  {{ pillar['rbd-path'] }}/etc/rbd-api/region.goodrain.me/ssl/client.key.pem