version: '2.1'
services:
  rbd-dns:
    image: rainbond/rbd-dns:{{ pillar['rbd-version'] }}
    container_name: rbd-dns
    environment:
    - KUBEURL=http://127.0.0.1:8181
    - FORWARD={{ pillar['dns'] }},114.114.114.114
    - SKYDNS_DOMAIN=goodrain.me
    - RECORD_1=goodrain.me:{{ pillar['inet-ip'] }}
    - RECORD_2=lang.goodrain.me:{{ pillar['inet-ip'] }}
    - RECORD_3=maven.goodrain.me:{{ pillar['inet-ip'] }}
    - RECORD_4=console.goodrain.me:{{ pillar['inet-ip'] }}
    - RECORD_5=region.goodrain.me:{{ pillar['inet-ip'] }}
    - RECORD_6=kubeapi.goodrain.me:{{ pillar['inet-ip'] }}
    logging:
      driver: json-file
      options:
        max-size: 50m
        max-file: '3'
    network_mode: host
    restart: always
  rbd-hub:
    image: rainbond/rbd-registry:2.3.1
    container_name: rbd-hub
    volumes:
    - /grdata/services/registry/:/var/lib/registry
    logging:
      driver: json-file
      options:
        max-size: 50m
        max-file: '3'
    network_mode: host
    restart: always
  rbd-eventlog:
    image: rainbond/rbd-eventlog:{{ pillar['rbd-version'] }}
    container_name: rbd-eventlog
    environment:
      MYSQL_HOST: {{ pillar['database']['mysql']['host'] }}
      MYSQL_PORT: {{ pillar['database']['mysql']['port'] }}
      MYSQL_USER: {{ pillar['database']['mysql']['user'] }}
      MYSQL_PASSWORD: {{ pillar['database']['mysql']['pass'] }}
      MYSQL_DATABASE: region
      K8S_MASTER: http://127.0.0.1:8181
      CLUSTER_BIND_IP: {{ pillar['inet-ip'] }}
    volumes:
    - {{ pillar['rbd-path'] }}/logs/rbd-eventlog:/var/log
    - /grdata/downloads/log:/grdata/logs
    logging:
      driver: json-file
      options:
        max-size: 50m
        max-file: '3'
    network_mode: host
    restart: always
  rbd-entrance:
    image: rainbond/rbd-entrance:{{ pillar['rbd-version'] }}
    container_name: rbd-entrance
    logging:
      driver: json-file
      options:
        max-size: 50m
        max-file: '3'
    network_mode: host
    restart: always
    environment:
      DEFAULT_HTTP_PORT: 80
      DEFAULT_HTTPS_PORT: 443
    volumes:
    - {{ pillar['rbd-path'] }}/etc/kubernetes/kubecfg:/etc/goodrain/kubernetes
    command:
    - --plugin-name=openresty
    - --plugin-opts=urls=http://127.0.0.1:10002
    - --kube-conf=/etc/goodrain/kubernetes/admin.kubeconfig
    - --log-level=info
    - --etcd-endpoints http://127.0.0.1:2379
  rbd-api:
    image: rainbond/rbd-api:{{ pillar['rbd-version'] }}
    container_name: rbd-api
    environment:
      REGION_TAG: {{ pillar['rbd-tag'] }}
      EX_DOMAIN: {{ pillar['domain'] }}
      LicenseSwitch: 'off'
    volumes:
    - /grdata:/grdata
    - {{ pillar['rbd-path'] }}/etc/rbd-api:/etc/goodrain
    - {{ pillar['rbd-path'] }}/etc/kubernetes/kubecfg:/etc/goodrain/kubernetes
    - {{ pillar['rbd-path'] }}/logs/docker_logs:/data/docker_logs
    - {{ pillar['rbd-path'] }}/logs/rbd-api:/logs
    command: --log-level=debug --mysql="{{ pillar['database']['mysql']['user'] }}:{{ pillar['database']['mysql']['pass'] }}@tcp({{ pillar['database']['mysql']['host'] }}:{{ pillar['database']['mysql']['port'] }})/region"
    logging:
      driver: json-file
      options:
        max-size: 50m
        max-file: '3'
    network_mode: host
    restart: always
  rbd-chaos:
    image: rainbond/rbd-chaos:{{ pillar['rbd-version'] }}
    container_name: rbd-chaos
    command: --log-level=debug --mysql="{{ pillar['database']['mysql']['user'] }}:{{ pillar['database']['mysql']['pass'] }}@tcp({{ pillar['database']['mysql']['host'] }}:{{ pillar['database']['mysql']['port'] }})/region"
    environment:
    - SOURCE_DIR=/cache/source
    - CACHE_DIR=/cache
    logging:
      driver: json-file
      options:
        max-size: 50m
        max-file: '3'
    volumes:
    - /logs:/logs
    - /grdata:/grdata
    - /cache:/cache
    - /var/run:/var/run
    - {{ pillar['rbd-path'] }}/etc/rbd-chaos/ssh:/root/.ssh
    network_mode: host
    restart: always
  rbd-lb:
    image: rainbond/rbd-lb:{{ pillar['rbd-version'] }}
    container_name: rbd-lb
    environment:
      DEFAULT_PORT: 80
      HTTP_SUFFIX_URL: {{ pillar['domain'] }}
    volumes:
    - {{ pillar['rbd-path'] }}/etc/rbd-lb/dynamics:/usr/local/openresty/nginx/conf/dynamics
    logging:
      driver: json-file
      options:
        max-size: 50m
        max-file: '3'
    network_mode: host
    restart: always
  rbd-mq:
    image: rainbond/rbd-mq:{{ pillar['rbd-version'] }}
    container_name: rbd-mq
    command: --log-level=debug
    logging:
      driver: json-file
      options:
        max-size: 50m
        max-file: '3'
    network_mode: host
    restart: always
  rbd-webcli:
    image: rainbond/rbd-webcli:{{ pillar['rbd-version'] }}
    container_name: rbd-webcli
    volumes:
    - /usr/local/bin/kubectl:/usr/bin/kubectl
    - /root/.kube:/root/.kube
    command: --hostIP={{ pillar['inet-ip'] }}
    logging:
      driver: json-file
      options:
        max-size: 50m
        max-file: '3'
    network_mode: host
    restart: always
  rbd-app-ui:
    image: rainbond/rbd-app-ui:{{ pillar['rbd-version'] }}
    container_name: rbd-app-ui
    environment:
      MANAGE_SECRET_KEY: {{ pillar['secretkey'] }}
      REGION_TAG: {{ pillar['rbd-tag'] }}
      MYSQL_HOST: {{ pillar['database']['mysql']['host'] }}
      MYSQL_PORT: {{ pillar['database']['mysql']['port'] }}
      MYSQL_USER: {{ pillar['database']['mysql']['user'] }}
      MYSQL_PASS: {{ pillar['database']['mysql']['pass'] }}
      MYSQL_DB: console
    volumes:
    - /grdata/services/console:/data
    - {{ pillar['rbd-path'] }}/logs/rbd-app-ui/goodrain.log:/tmp/goodrain.log
    logging:
      driver: json-file
      options:
        max-size: 50m
        max-file: '3'
    network_mode: host
    restart: always
{% if grains['id'] == "manage01" %}
  rbd-db:
    image: rainbond/rbd-db:{{ pillar['rbd-version'] }}
    container_name: rbd-db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    volumes:
    - {{ pillar['rbd-path'] }}/data/rbd-db:/data
    - {{ pillar['rbd-path'] }}/etc/rbd-db:/etc/mysql
    logging:
      driver: json-file
      options:
        max-size: 50m
        max-file: '3'
    network_mode: host
    restart: always
  rbd-worker:
    image: rainbond/rbd-worker:{{ pillar['rbd-version'] }}
    container_name: rbd-worker
    environment:
      MYSQL_HOST: {{ pillar['database']['mysql']['host'] }}
      MYSQL_PORT: {{ pillar['database']['mysql']['port'] }}
      MYSQL_USER: {{ pillar['database']['mysql']['user'] }}
      MYSQL_PASSWORD: {{ pillar['database']['mysql']['pass'] }}
      MYSQL_DATABASE: region
      K8S_MASTER: http://127.0.0.1:8181
      CUR_NET: calico
      EX_DOMAIN: {{ pillar['domain'] }}
    volumes:
    - {{ pillar['rbd-path'] }}/etc/kubernetes/kubecfg:/etc/goodrain/kubernetes
    - /grdata:/grdata
    command: --log-level=info --kube-config="/etc/goodrain/kubernetes/admin.kubeconfig"
      --mysql="{{ pillar['database']['mysql']['user'] }}:{{ pillar['database']['mysql']['pass'] }}@tcp({{ pillar['database']['mysql']['host'] }}:{{ pillar['database']['mysql']['port'] }})/region"
    logging:
      driver: json-file
      options:
        max-size: 50m
        max-file: '3'
    network_mode: host
    restart: always
  rbd-repo:
    image: rainbond/rbd-repo:{{ pillar['rbd-version'] }}
    container_name: rbd-repo
    volumes:
    - /grdata/services/artifactory-{{ grains['nodename'] }}:/var/opt/jfrog/artifactory
    logging:
      driver: json-file
      options:
        max-size: 50m
        max-file: '3'
    network_mode: host
    restart: always
  prometheus:
    image: rainbond/prometheus:v2.0.0
    container_name: prometheus
    volumes:
    - /grdata/services/prometheus/data:/prometheusdata
    - {{ pillar['rbd-path'] }}/etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command: --web.listen-address=":9999" --storage.tsdb.path="/prometheusdata" --storage.tsdb.retention=7d --config.file="/etc/prometheus/prometheus.yml"
    logging:
      driver: json-file
      options:
        max-size: 50m
        max-file: '3'
    network_mode: host
    restart: always
{% endif %}
