version: '2.1'
services:
  rbd-dns:
    image: {{ pillar['public-image-domain'] }}/{{ pillar['rainbond-modules']['rbd-dns']['image'] }}:{{ pillar['rainbond-modules']['rbd-dns']['version'] }}
    container_name: rbd-dns
    mem_limit: 1024M
    environment:
      - VERBOSE=true
    command:
    - --kubecfg-file=/etc/kubernetes/admin.kubeconfig
    - --v=3
    - --healthz-port=8089
    - --nameservers={{ pillar.dns.get('current','114.114.114.114') }},{{ pillar.dns.slave }}
    - --recoders=goodrain.me={{ pillar['master-private-ip'] }},*.goodrain.me={{ pillar['master-private-ip'] }}
    volumes:
    - {{ pillar['rbd-path'] }}/etc/kubernetes/kubecfg:/etc/kubernetes
    logging:
      driver: json-file
      options:
        max-size: 50m
        max-file: '3'
    network_mode: host
    restart: always
  rbd-hub:
    image: {{ pillar['public-image-domain'] }}/{{ pillar['rainbond-modules']['rbd-registry']['image'] }}:{{ pillar['rainbond-modules']['rbd-registry']['version'] }}
    container_name: rbd-hub
    volumes:
    - /grdata/services/registry/:/var/lib/registry
    logging:
      driver: json-file
      options:
        max-size: 50m
        max-file: '3'
    network_mode: host
    restart: always
  rbd-repo:
    image: {{ pillar['public-image-domain'] }}/{{ pillar['rainbond-modules']['rbd-repo']['image'] }}:{{ pillar['rainbond-modules']['rbd-repo']['version'] }}
    container_name: rbd-repo
    volumes:
    - /grdata/services/artifactory-{{ grains['nodename'] }}:/var/opt/jfrog/artifactory
    logging:
      driver: json-file
      options:
        max-size: 50m
        max-file: '3'
    network_mode: host
    restart: always

  rbd-entrance:
    image: {{ pillar['public-image-domain'] }}/{{ pillar['rainbond-modules']['rbd-entrance']['image'] }}:{{ pillar['rainbond-modules']['rbd-entrance']['version'] }}
    container_name: rbd-entrance
    mem_limit: 1024M
    logging:
      driver: json-file
      options:
        max-size: 50m
        max-file: '3'
    network_mode: host
    restart: always
    environment:
      DEFAULT_HTTP_PORT: 80
      DEFAULT_HTTPS_PORT: 443
    volumes:
    - {{ pillar['rbd-path'] }}/etc/kubernetes/kubecfg:/etc/goodrain/kubernetes
    command:
    - --plugin-name=openresty
    - --plugin-opts=urls=http://127.0.0.1:10002
    - --kube-conf=/etc/goodrain/kubernetes/admin.kubeconfig
    - --log-level=info
    - --etcd-endpoints http://127.0.0.1:2379
    - --run-mode=sync
  rbd-api:
    image: {{ pillar['public-image-domain'] }}/{{ pillar['rainbond-modules']['rbd-api']['image'] }}:{{ pillar['rainbond-modules']['rbd-api']['version'] }}
    container_name: rbd-api
    mem_limit: 1024M
    environment:
      REGION_TAG: {{ pillar['rbd-tag'] }}
      EX_DOMAIN: {{ pillar['domain'] }}
      LicenseSwitch: 'off'
    volumes:
    - /grdata:/grdata
    - {{ pillar['rbd-path'] }}/etc/rbd-api:/etc/goodrain
    - {{ pillar['rbd-path'] }}/etc/kubernetes/kubecfg:/etc/goodrain/kubernetes
    - {{ pillar['rbd-path'] }}/logs/docker_logs:/data/docker_logs
    - {{ pillar['rbd-path'] }}/logs/rbd-api:/logs
    command: --log-level=debug --mysql="{{ pillar['database']['mysql']['user'] }}:{{ pillar['database']['mysql']['pass'] }}@tcp({{ pillar['database']['mysql']['host'] }}:{{ pillar['database']['mysql']['port'] }})/region"
    logging:
      driver: json-file
      options:
        max-size: 50m
        max-file: '3'
    network_mode: host
    restart: always
  rbd-chaos:
    image: {{ pillar['public-image-domain'] }}/{{ pillar['rainbond-modules']['rbd-chaos']['image'] }}:{{ pillar['rainbond-modules']['rbd-chaos']['version'] }}
    container_name: rbd-chaos
    mem_limit: 1024M
    command: --log-level=debug --mysql="{{ pillar['database']['mysql']['user'] }}:{{ pillar['database']['mysql']['pass'] }}@tcp({{ pillar['database']['mysql']['host'] }}:{{ pillar['database']['mysql']['port'] }})/region"
    environment:
    - SOURCE_DIR=/cache/source
    - CACHE_DIR=/cache
    logging:
      driver: json-file
      options:
        max-size: 50m
        max-file: '3'
    volumes:
    - /logs:/logs
    - /grdata:/grdata
    - /cache:/cache
    - /var/run:/var/run
    - {{ pillar['rbd-path'] }}/etc/rbd-chaos/ssh:/root/.ssh
    network_mode: host
    restart: always
  rbd-lb:
    image: {{ pillar['public-image-domain'] }}/{{ pillar['rainbond-modules']['rbd-lb']['image'] }}:{{ pillar['rainbond-modules']['rbd-lb']['version'] }}
    container_name: rbd-lb
    environment:
      DEFAULT_PORT: 80
      HTTP_SUFFIX_URL: {{ pillar['domain'] }}
    volumes:
    - {{ pillar['install-script-path'] }}:{{ pillar['install-script-path'] }}
    - {{ pillar['rbd-path'] }}/etc/rbd-lb/dynamics:/usr/local/openresty/nginx/conf/dynamics
    - {{ pillar['rbd-path'] }}/logs/rbd-lb:/usr/local/openresty/nginx/logs
    logging:
      driver: json-file
      options:
        max-size: 50m
        max-file: '3'
    network_mode: host
    restart: always
  rbd-mq:
    image: {{ pillar['public-image-domain'] }}/{{ pillar['rainbond-modules']['rbd-mq']['image'] }}:{{ pillar['rainbond-modules']['rbd-mq']['version'] }}
    container_name: rbd-mq
    mem_limit: 1024M
    command: --log-level=debug
    logging:
      driver: json-file
      options:
        max-size: 50m
        max-file: '3'
    network_mode: host
    restart: always
  rbd-webcli:
    image: {{ pillar['public-image-domain'] }}/{{ pillar['rainbond-modules']['rbd-webcli']['image'] }}:{{ pillar['rainbond-modules']['rbd-webcli']['version'] }}
    container_name: rbd-webcli
    mem_limit: 1024M
    volumes:
    - /usr/local/bin/kubectl:/usr/bin/kubectl
    - /root/.kube:/root/.kube
    command: --hostIP={{ pillar['master-private-ip'] }}
    logging:
      driver: json-file
      options:
        max-size: 50m
        max-file: '3'
    network_mode: host
    restart: always
  rbd-app-ui:
    image: {{ pillar['public-image-domain'] }}/{{ pillar['rainbond-modules']['rbd-app-ui']['image'] }}:{{ pillar['rainbond-modules']['rbd-app-ui']['version'] }}
    container_name: rbd-app-ui
    environment:
      MANAGE_SECRET_KEY: {{ pillar['secretkey'] }}
      REGION_TAG: {{ pillar['rbd-tag'] }}
      MYSQL_HOST: {{ pillar['database']['mysql']['host'] }}
      MYSQL_PORT: {{ pillar['database']['mysql']['port'] }}
      MYSQL_USER: {{ pillar['database']['mysql']['user'] }}
      MYSQL_PASS: {{ pillar['database']['mysql']['pass'] }}
      MYSQL_DB: console
    volumes:
    - /grdata/services/console:/data
    - {{ pillar['rbd-path'] }}/logs/rbd-app-ui/goodrain.log:/tmp/goodrain.log
    logging:
      driver: json-file
      options:
        max-size: 50m
        max-file: '3'
    network_mode: host
    restart: always
  rbd-worker:
    image: {{ pillar['public-image-domain'] }}/{{ pillar['rainbond-modules']['rbd-worker']['image'] }}:{{ pillar['rainbond-modules']['rbd-worker']['version'] }}
    container_name: rbd-worker
    mem_limit: 1024M
    environment:
      K8S_MASTER: http://127.0.0.1:8181
      CUR_NET: calico
      EX_DOMAIN: {{ pillar['domain'] }}
    volumes:
    - {{ pillar['rbd-path'] }}/etc/kubernetes/kubecfg:/etc/goodrain/kubernetes
    - /grdata:/grdata
    command: --log-level=info --kube-config="/etc/goodrain/kubernetes/admin.kubeconfig"
      --mysql="{{ pillar['database']['mysql']['user'] }}:{{ pillar['database']['mysql']['pass'] }}@tcp({{ pillar['database']['mysql']['host'] }}:{{ pillar['database']['mysql']['port'] }})/region"
    logging:
      driver: json-file
      options:
        max-size: 50m
        max-file: '3'
    network_mode: host
    restart: always
{% if grains['id'] == "manage01" %}
  rbd-db:
    image: {{ pillar['public-image-domain'] }}/{{ pillar['database']['mysql']['image'] }}:{{ pillar['database']['mysql']['version'] }}
    container_name: rbd-db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    volumes:
    - {{ pillar['rbd-path'] }}/data/rbd-db:/data
    - {{ pillar['rbd-path'] }}/etc/rbd-db:/etc/mysql
    logging:
      driver: json-file
      options:
        max-size: 50m
        max-file: '3'
    network_mode: host
    restart: always
  rbd-prometheus:
    image: {{ pillar['public-image-domain'] }}/{{ pillar['rainbond-modules']['rbd-prometheus']['image'] }}:{{ pillar['rainbond-modules']['rbd-prometheus']['version'] }}
    container_name: rbd-prometheus
    user: "200"
    volumes:
    - {{ pillar['rbd-path'] }}/data/prom:/prometheusdata
    - {{ pillar['rbd-path'] }}/etc/rbd-prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command: --web.listen-address=":9999" --storage.tsdb.path="/prometheusdata" --storage.tsdb.retention=7d --config.file="/etc/prometheus/prometheus.yml"
    logging:
      driver: json-file
      options:
        max-size: 50m
        max-file: '3'
    network_mode: host
    restart: always
{% endif %}
  rbd-eventlog:
    image: {{ pillar['public-image-domain'] }}/{{ pillar['rainbond-modules']['rbd-eventlog']['image'] }}:{{ pillar['rainbond-modules']['rbd-eventlog']['version'] }}
    container_name: rbd-eventlog
    mem_limit: 1024M
    environment:
      MYSQL_HOST: {{ pillar['database']['mysql']['host'] }}
      MYSQL_PORT: {{ pillar['database']['mysql']['port'] }}
      MYSQL_USER: {{ pillar['database']['mysql']['user'] }}
      MYSQL_PASSWORD: {{ pillar['database']['mysql']['pass'] }}
      MYSQL_DATABASE: region
      K8S_MASTER: http://127.0.0.1:8181
      CLUSTER_BIND_IP: {{ pillar['master-private-ip'] }}
    volumes:
    - {{ pillar['rbd-path'] }}/logs/rbd-eventlog:/var/log
    - /grdata/downloads/log:/grdata/logs
    logging:
      driver: json-file
      options:
        max-size: 50m
        max-file: '3'
    network_mode: host
    restart: always
